import { buildSchema } from "graphql";
import ts from "typescript";
import tempy from "tempy";
import path from "path";
import { printSchemaTypes } from "./schema";

const gql = ([s]: TemplateStringsArray) => buildSchema(s);

function s(string: string): string {
  const file = tempy.writeSync(string, { name: "@schema.d.ts" });
  const program = ts.createProgram({
    rootNames: [file],
    options: { strict: true, skipDefaultLibCheck: true, types: [] },
  });
  const diagnostics = ts.getPreEmitDiagnostics(program);
  const formattedDiagnostics = ts.formatDiagnostics(diagnostics, {
    getNewLine: () => "\n",
    getCanonicalFileName: (filename) => filename,
    getCurrentDirectory: () => path.dirname(file),
  });
  if (formattedDiagnostics !== "") {
    throw new Error(`input:\n${string}\n\nerror:\n${formattedDiagnostics}`);
  }
  return string;
}

test("syntax error", () => {
  let err;
  try {
    s("type a");
  } catch (e) {
    err = e;
  }

  expect(err).toMatchInlineSnapshot(`
    [Error: input:
    type a

    error:
    @schema.d.ts(1,7): error TS1005: '=' expected.
    ]
  `);
});

test("semantic error", () => {
  let err;
  try {
    s("type a = b;");
  } catch (e) {
    err = e;
  }

  expect(err).toMatchInlineSnapshot(`
    [Error: input:
    type a = b;

    error:
    @schema.d.ts(1,10): error TS2304: Cannot find name 'b'.
    ]
  `);
});

const schema = gql`
  type Query {
    thing(thing: SomeInput!): String
  }

  scalar UnknownCustomScalar
  scalar SomeCustomScalar

  input SomeInput {
    id: ID!
    nullableId: ID
    int: Int
    float: Float
    bool: Boolean
    string: String
    defaultedNullable: String = "default"
    defaultedNonNullable: String! = "default"
    listWithNullableElement: [String!]
    list: [String]
    other: OtherInput
    custom: SomeCustomScalar
    unknown: UnknownCustomScalar
  }
  input OtherInput {
    something: ID!
  }
`;
test("basic", () => {
  expect(
    s(
      printSchemaTypes({
        schema,
        readonly: false,
        scalars: {
          SomeCustomScalar: "string",
        },
      })
    )
  ).toMatchInlineSnapshot(`
    "/** @deprecated This should not be used outside of code generated by ts-gql */
    export type Maybe<T> = T | null;
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type InputMaybe<T> = Maybe<T>;
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };

    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type Scalars = {
      String: string;
      Int: number;
      Float: number;
      Boolean: boolean;
      ID: string;
      UnknownCustomScalar: UnknownCustomScalar;
      SomeCustomScalar: SomeCustomScalar;
    };

    export type Query = {
      __typename: "Query";
      thing: string | null;
    };

    export type QuerythingArgs = {
      thing: SomeInput;
    };

    export type UnknownCustomScalar = any;

    export type SomeCustomScalar = string;

    export type SomeInput = {
      id: string;
      nullableId?: string | null;
      int?: number | null;
      float?: number | null;
      bool?: boolean | null;
      string?: string | null;
      defaultedNullable?: string | null;
      defaultedNonNullable?: string;
      listWithNullableElement?: TSGQLMaybeArray<string> | null;
      list?: TSGQLMaybeArray<string | null> | null;
      other?: OtherInput | null;
      custom?: SomeCustomScalar | null;
      unknown?: UnknownCustomScalar | null;
    };

    export type OtherInput = {
      something: string;
    };

    type TSGQLMaybeArray<T> = Array<T> | T

    export {};"
  `);
});

test("readonly", () => {
  expect(
    s(
      printSchemaTypes({
        schema,
        readonly: true,
        scalars: {
          SomeCustomScalar: "string",
        },
      })
    )
  ).toMatchInlineSnapshot(`
    "/** @deprecated This should not be used outside of code generated by ts-gql */
    export type Maybe<T> = T | null;
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type InputMaybe<T> = Maybe<T>;
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };

    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type Scalars = {
      String: string;
      Int: number;
      Float: number;
      Boolean: boolean;
      ID: string;
      UnknownCustomScalar: UnknownCustomScalar;
      SomeCustomScalar: SomeCustomScalar;
    };

    export type Query = {
      readonly __typename: "Query";
      readonly thing: string | null;
    };

    export type QuerythingArgs = {
      readonly thing: SomeInput;
    };

    export type UnknownCustomScalar = any;

    export type SomeCustomScalar = string;

    export type SomeInput = {
      readonly id: string;
      readonly nullableId?: string | null;
      readonly int?: number | null;
      readonly float?: number | null;
      readonly bool?: boolean | null;
      readonly string?: string | null;
      readonly defaultedNullable?: string | null;
      readonly defaultedNonNullable?: string;
      readonly listWithNullableElement?: TSGQLMaybeArray<string> | null;
      readonly list?: TSGQLMaybeArray<string | null> | null;
      readonly other?: OtherInput | null;
      readonly custom?: SomeCustomScalar | null;
      readonly unknown?: UnknownCustomScalar | null;
    };

    export type OtherInput = {
      readonly something: string;
    };

    type TSGQLMaybeArray<T> = ReadonlyArray<T> | T

    export {};"
  `);
});

test("overriding built in scalar", () => {
  expect(
    s(
      printSchemaTypes({
        schema,
        readonly: true,
        scalars: {
          SomeCustomScalar: "string",
          ID: "string | number",
        },
      })
    )
  ).toMatchInlineSnapshot(`
    "/** @deprecated This should not be used outside of code generated by ts-gql */
    export type Maybe<T> = T | null;
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type InputMaybe<T> = Maybe<T>;
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };

    /** @deprecated This should not be used outside of code generated by ts-gql */
    export type Scalars = {
      String: string;
      Int: number;
      Float: number;
      Boolean: boolean;
      ID: ID;
      UnknownCustomScalar: UnknownCustomScalar;
      SomeCustomScalar: SomeCustomScalar;
    };

    export type ID = string | number;

    export type Query = {
      readonly __typename: "Query";
      readonly thing: string | null;
    };

    export type QuerythingArgs = {
      readonly thing: SomeInput;
    };

    export type UnknownCustomScalar = any;

    export type SomeCustomScalar = string;

    export type SomeInput = {
      readonly id: ID;
      readonly nullableId?: ID | null;
      readonly int?: number | null;
      readonly float?: number | null;
      readonly bool?: boolean | null;
      readonly string?: string | null;
      readonly defaultedNullable?: string | null;
      readonly defaultedNonNullable?: string;
      readonly listWithNullableElement?: TSGQLMaybeArray<string> | null;
      readonly list?: TSGQLMaybeArray<string | null> | null;
      readonly other?: OtherInput | null;
      readonly custom?: SomeCustomScalar | null;
      readonly unknown?: UnknownCustomScalar | null;
    };

    export type OtherInput = {
      readonly something: ID;
    };

    type TSGQLMaybeArray<T> = ReadonlyArray<T> | T

    export {};"
  `);
});
