name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-v5-ubuntu-latest-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-v5-ubuntu-latest-

      - name: Install pnpm
        run: npm i -g pnpm@6.19.0

      - name: Install Dependencies
        run: pnpm i

      - name: Build types for test app
        run: cd test-app && pnpx ts-gql build

      - name: Check Types
        run: pnpm run types
  tests:
    name: "Tests on ${{matrix.platform}}"
    strategy:
      fail-fast: true
      matrix:
        platform:
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ matrix.platform }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ matrix.platform }}-

      - name: Install pnpm
        run: npm i -g pnpm@6.19.0

      - name: Install Dependencies
        run: pnpm i

      - name: Run Tests
        run: pnpm run test
