name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/ci-setup

      - name: Check Types
        run: pnpm run types
  tests:
    name: "Tests on ${{matrix.platform}}"
    strategy:
      fail-fast: true
      matrix:
        platform:
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/ci-setup

      - name: Run Tests
        run: pnpm run test
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/ci-setup

      - name: ESLint
        run: pnpm run lint
      - name: Prettier
        run: pnpm run format:check
